- name: Install nginx
  package:
    name: nginx
    state: latest

- name: Copy nginx.conf
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf  

- name: Copy service-a config file
  copy:
    src: "{{ role_path }}/files/service-a.conf"
    dest: /etc/nginx/conf.d/service-a.conf

- name: Copy service-b config file
  copy:
    src: "{{ role_path }}/files/service-b.conf"
    dest: /etc/nginx/conf.d/service-b.conf    

- name: nginx | ensure service is running
  systemd:
    name: nginx
    state: started
    enabled: true          

### sysctl setting

- sysctl:
    name: net.core.somaxconn
    value: '65536'
    sysctl_set: true
    state: present
    reload: true 


- sysctl:
    name: net.core.netdev_max_backlog
    value: '5000'
    sysctl_set: true
    state: present
    reload: true

- sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: '1440000'
    sysctl_set: true
    state: present
    reload: true

- sysctl:
    name: fs.file-max
    value: '50000'
    sysctl_set: true
    state: present
    reload: true 

- sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: '15'
    sysctl_set: true
    state: present
    reload: true

- name: nginx ulimit settings
  copy:
    src: "{{ role_path }}/files/nginx_ulimit.conf"
    dest: /etc/security/limits.d/nginx.conf
